AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  photo-app-users-api-cognito

  Sample SAM Template for photo-app-users-api-cognito

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  CreateUserHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PhotoAppCognito
      Handler: com.appsdeveloperblog.aws.lambda.CreateUserHandler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          COGNITO_POOL_APP_CLIENT_ID: 4vi58e9iq8htmgeadqoj9ll05r
          COGNITO_POOL_APP_CLIENT_SECRET: 6pfsrdmsfmm3d36lblbqjhfl05u7o40nkmffaa0tbmkg8t7ep7e
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /users
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateUserApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateUserHandler Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CreateUserHandlerFunction:
    Description: "CreateUserHandler Lambda Function ARN"
    Value: !GetAtt CreateUserHandlerFunction.Arn
  CreateUserHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for CreateUserHandler"
    Value: !GetAtt CreateUserHandlerFunctionRole.Arn
